theme = "zarya"
baseURL = "http://gabeamaya.com"
languageCode = "en-us"
title = "Gabe Amaya's Journal"
MetaDataFormat = "toml"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params] # theme parameters
    author = "Gabe Amaya" # author's name
    info = "Front End Web Developer" # author's job title or info
    description = "" # site description
    keywords = "blog,developer,personal" # site keywords
    
# Social links
[[params.social]]
    icon = "github"
    icon_pack = "fa"
    name = "GitHub"
    weight = 1
    url = "https://github.com/CodingGabe/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/King_Gabe/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/GabeAmaya/"

# Menu items

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Journal"
    weight = 2
    url = "/journal/"